DROP TABLE IF EXISTS tracks;
DROP TABLE IF EXISTS genres;


CREATE TABLE tracks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT UNIQUE NOT NULL,
  artist TEXT NOT NULL,
  genre_id TEXT NOT NULL,
  track_length INTEGER NOT NULL
);

CREATE TABLE genres (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT UNIQUE NOT NULL
);